=== tjhartline/CS305/CS 305 Module Six Code/rest-service/suppression1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="suppressions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="suppress" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="notes" maxOccurs="unbounded" type="xs:string" />
							<xs:element name="packageUrl">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="regex" type="xs:boolean" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="cve" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tjhartline/CS305/CS 305 Module Six Code/rest-service/suppression.xml
<suppressions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="suppression1.xsd">

  <suppress>
    <notes><![CDATA[
    file name: bcprov-jdk15on-1.46.jar
    ]]></notes>
    <packageUrl regex="true">^pkg:maven/org\.bouncycastle/bcprov\-jdk15on@.*$</packageUrl>
    <cve>CVE-2013-1624</cve>
  </suppress>

  <suppress>
    <notes><![CDATA[
    file name: jackson-databind-2.10.2.jar
    ]]></notes>
    <packageUrl regex="true">^pkg:maven/com\.fasterxml\.jackson\.core/jackson\-databind@.*$</packageUrl>
    <cve>CVE-2023-35116</cve>
  </suppress>

  <suppress>
    <notes>This has been flagged as no longer used for mapping as it is now a category.</notes>
    <notes><![CDATA[
    file name: bcprov-jdk15on-1.46.jar
    ]]></notes>
    <packageUrl regex="true">^pkg:maven/org\.bouncycastle/bcprov\-jdk15on@.*$</packageUrl>
    <cve>CVE-2016-1000346</cve>
  </suppress>

</suppressions>
